#!/bin/sh
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq2.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq3.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq4.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq5.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq6.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq7.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq8.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq1.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq3.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq4.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq5.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq6.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq7.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq8.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq2.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq4.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq5.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq6.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq7.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq8.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq3.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq5.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq6.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq7.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq8.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq4.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq5.txt -s2 ../seqs/seq6.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq5.txt -s2 ../seqs/seq7.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq5.txt -s2 ../seqs/seq8.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq5.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq5.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq5.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq5.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq6.txt -s2 ../seqs/seq7.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq6.txt -s2 ../seqs/seq8.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq6.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq6.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq6.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq6.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq7.txt -s2 ../seqs/seq8.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq7.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq7.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq7.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq7.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq8.txt -s2 ../seqs/seq9.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq8.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq8.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq8.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq9.txt -s2 ../seqs/seq10.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq9.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq9.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq10.txt -s2 ../seqs/seq11.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq10.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1
python3 dynamic_needleman_wunsch.py -s1 ../seqs/seq11.txt -s2 ../seqs/seq12.txt -m 1 -mm -1 -g -1